### ISSUE TITLE
AWSSCV_Salesforce_Validator ---- Lambda failed

### ISSUE THREAD

**Issue by raghava1996** [amazon-connect/amazon-connect-salesforce-scv#103]
Hi

When i try to run the AWSSCV_Salesforce_Validator lambda to test I'm getting this error

[DEBUG]	2022-05-23T10:19:20.395Z	48e820c1-59f4-4e21-97ee-8c53b08b1d4f	Event needs-retry.secrets-manager.GetSecretValue: calling handler <botocore.retryhandler.RetryHandler object at 0x7fcc19fe24f0>
[DEBUG]	2022-05-23T10:19:20.395Z	48e820c1-59f4-4e21-97ee-8c53b08b1d4f	No retry needed.
[DEBUG]	2022-05-23T10:19:20.395Z	48e820c1-59f4-4e21-97ee-8c53b08b1d4f	Creating new access token...
[DEBUG]	2022-05-23T10:19:20.395Z	48e820c1-59f4-4e21-97ee-8c53b08b1d4f	{'iss': '3MVG9XfKTWtUp0bIryhqAJbzDDksPNSrOO6uHe4yOnuCekPh5eK4LqPR9d9fgnzEintdHUZ_btZSGF1wyrant', 'sub': 'awsutil@bostonprivate--full.my.salesforce.com', 'aud': 'https://test.salesforce.com', 'exp': 1653301280}
[DEBUG]	2022-05-23T10:19:21.564Z	48e820c1-59f4-4e21-97ee-8c53b08b1d4f	eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiIzTVZHOVhmS1RXdFVwMGJJcnlocUFKYnpERGtzUE5Tck9PNnVIZTR5T251Q2VrUGg1ZUs0THFQUjlkOWZnbnpFaW50ZEhVWl9idFpTR0Yxd3lyYW50Iiwic3ViIjoiYXdzdXRpbEBib3N0b25wcml2YXRlLS1mdWxsLm15LnNhbGVzZm9yY2UuY29tIiwiYXVkIjoiaHR0cHM6Ly90ZXN0LnNhbGVzZm9yY2UuY29tIiwiZXhwIjoxNjUzMzAxMjgwfQ.QTfGz1EMiEYUh6RCpalcAiXn3X9pdHNkPB8fQpMOdLNUxaX2CArmtl2cMDg0_t-PpeHapDzPizUuJyAJ8YC8qNV_4VIBhOhNwiBmp2zhQtUaenhwhDsiieg2WlOCe7LbQgRDc4WzN--65EWZAr9tAzu8VkTHt8lfvqGpdWVVjQOcKFOVnXRgtYVxUUgnYusJ03Ibib7wHfpenIlwu8FDllh2JNQRkp2F2LXp9qqzihmp9nIAbSlQdq2bBsRW7CMmh1QO1nHHjMIJSjUK-XwvLeL8rT9UvbIzyRk9gkVTw0WsoSGY30w-RKxdqKk414p9gr4NBAl91BL6ylByfY9SSQ
[DEBUG]	2022-05-23T10:19:21.622Z	48e820c1-59f4-4e21-97ee-8c53b08b1d4f	Starting new HTTPS connection (1): test.salesforce.com:443
[DEBUG]	2022-05-23T10:19:21.824Z	48e820c1-59f4-4e21-97ee-8c53b08b1d4f	https://test.salesforce.com:443 "POST /services/oauth2/token HTTP/1.1" 400 None
[DEBUG]	2022-05-23T10:19:21.827Z	48e820c1-59f4-4e21-97ee-8c53b08b1d4f	<Response [400]>

**Comment by dougjaso** [comment]
Things to check: 
1.  Make sure you have the cert associated with your App
2. Make sure your api user has the right permission for the app
3. Make sure that you have the right keys set in your secrets
4. Make sure there are no spaces in your keys.

**Comment by konungr5583** [comment]
@raghava1996 did you resolve the problem ! I have the same error ':)
