### ISSUE TITLE
Case and Email

### ISSUE THREAD

**Issue by raghava1996** [amazon-connect/amazon-connect-salesforce-scv#105]
Hey

Is there any possibility to create a SF Case as well as to send an Email (Mentioned in the Queue Description QVMB:: ).
Also if the Voicemail is left for a specific user, is there a possibility to have a case assigned to that particular User.

**Comment by dougjaso** [comment]
It depends. If you are on the bundle versions of SCV, the existing configuration of VM uses services that are not allowed. If you are on the partner telephony version, then you could. You would just need to modify the code to do so, as right now it only looks for a single delivery option, but it is certainly possible to do.

When you leave a voicemail for a specific user, they are the owner of the case.

**Comment by vf-kenh** [comment]
@dougjaso 
SCV BYOA seems no problem with VMX2

It seems the VMX2 installs the SES ( regardless the delivery mode is email or SF case ), which isn't whitelisted/SCP in the SCV Native version.

Salesforce appears to promote it, but locks down on SES https://developer.salesforce.com/docs/atlas.en-us.voice_developer_guide.meta/voice_developer_guide/voice_connect_examples.htm

AWS is deprecating VMX1.

cross account maybe a workaround?, but messy. Neat solution is to have SFDC allow SES and any services required in VMX2.... Would probably need AWS to get in a room with SFDC to discuss this one out...

**Comment by dougjaso** [comment]
Email is not a valid option for SCV bundle versions, nor is Connect Tasks. Only the Salesforce Delivery Modes are valid. None of the email components are deployed if they are not selected. There is no intended workaround for Email in SCV Bundle deployments. One is certainly possible with cross account access, but there is no plan to offer non-salesforce delivery modes. 

As long as you don't enable email, you're fine. I have validated this, again, on a salesforce dev org with bundle license. It deploys without issue.
