### ISSUE TITLE
Salesforce Agent test creates case but Queue test does not.

### ISSUE THREAD

**Issue by chrisansotti** [amazon-connect/amazon-connect-salesforce-scv#125]
I've tried multiple queues as test queues but none of them are creating a case. I've triple checked the ARN and I installed the entire package in a sandbox just last week and it worked perfectly.

The Agent test works and is creating a case, not sure why Queue does not.

**Comment by dougjaso** [comment]
Does the queue you are using have a description?

Sent from my iPhone

On Aug 14, 2022, at 10:52 AM, chrisansotti ***@***.***> wrote:

﻿

I've tried multiple queues as test queues but none of them are creating a case. I've triple checked the ARN and I installed the entire package in a sandbox just last week and it worked perfectly.

The Agent test works and is creating a case, not sure why Queue does not.

**Comment by chrisansotti** [comment]
I just found that in the Discussion right before I saw this and added a description. Worked! Thank you!
