### ISSUE TITLE
How to Update Node.js 12 runtime to Node.js 14

### ISSUE THREAD

**Issue by mahammedraheem** [amazon-connect/amazon-connect-salesforce-scv#128]
Hi

Please help me on how to update Node.js 12 runtime to Node.js 14 Today I received the below email from amazon

**Hello,

We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Node.js 12 runtime.

We are ending support for Node.js 12 in AWS Lambda. This follows Node.js 12 End-Of-Life (EOL) reached on April 30, 2022 [1].

As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 14, 2022, Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions, and functions using Node.js 12 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 12 runtime. Starting December 14, 2022, you will no longer be able to update existing functions using the Node.js 12 runtime.

We recommend that you upgrade your existing Node.js 12 functions to Node.js 16 before November 14, 2022.**
![image](https://user-images.githubusercontent.com/28524562/185387713-508ce121-653c-4666-9da0-ad66e784ead0.png)

**Comment by dougjaso** [comment]
There will be an update package released prior to the November date.

**Comment by mahammedraheem** [comment]
Hi Douglas,

am unable to find the updated package, Could you please help me on where can find this updated package

Thanks in advance

**Comment by dougjaso** [comment]
It has not yet been released. As stated previously, it will be released prior to the November date.
