### ISSUE TITLE
SCVSalesforceValidator error

### ISSUE THREAD

**Issue by konungr5583** [amazon-connect/amazon-connect-salesforce-scv#133]
Hi,

When i try to excute the validator test function i got this error!

[DEBUG]	2022-08-25T08:41:17.639Z	5d6d3f01-817e-43db-b74d-117d6aadd6ec	Event needs-retry.secrets-manager.GetSecretValue: calling handler <botocore.retryhandler.RetryHandler object at 0x7febd669f850>
[DEBUG]	2022-08-25T08:41:17.639Z	5d6d3f01-817e-43db-b74d-117d6aadd6ec	No retry needed.
[DEBUG]	2022-08-25T08:41:17.639Z	5d6d3f01-817e-43db-b74d-117d6aadd6ec	Creating new access token...
[DEBUG]	2022-08-25T08:41:17.639Z	5d6d3f01-817e-43db-b74d-117d6aadd6ec	{'iss': '3MVG96mGXeuuwTZjEhDB3ZHdsbhtPx3WohjwKreSM8g7j8AN.jsy0bi8554nfNO1Q910PFnhRDrUcSZFlclPV', 'sub': 'awsutil@MyInstance.com', 'aud': 'https://login.salesforce.com', 'exp': 1661416997}
[DEBUG]	2022-08-25T08:41:18.808Z	5d6d3f01-817e-43db-b74d-117d6aadd6ec	eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiIzTVZHOTZtR1hldXV3VFpqRWhEQjNaSGRzYmh0UHgzV29oandLcmVTTThnN2o4QU4uanN5MGJpODU1NG5mTk8xUTkxMFBGbmhSRHJVY1NaRmxjbFBWIiwic3ViIjoiYXdzdXRpbEBpbWEtcGxhdGVmb3JtZS11cmdlbmNlLS1pbWF0ZWNoc2MuY29tIiwiYXVkIjoiaHR0cHM6Ly9sb2dpbi5zYWxlc2ZvcmNlLmNvbSIsImV4cCI6MTY2MTQxNjk5N30.saKNIIZL6tqEGNPc7SdmpsBRICBUg8zHBVJeAYcen8Fs7__tLVGkVFoim1dNJqB_kEOJxfMp7ro20vnHJz8AM_Cjr2yB_4W_KbxVDHVeISLk13TOF73hu4VwqoYb3BEsi65XWSDKuzxb_mOQX3mLuIKtOFX0bs0j02qnsHe8mcpeYSrOpLO2imUqce1hSdm8rDLZREIGVjjAsuib0MYSByBAcVFzqKfAi1d2-8scf1F-6dfsgB06ozzMlDWQpD6vqd5wOJ-S8QLekH4dJTGoa5g484DaHotgQs17rRdZai4zIVcz-jRmQf8I77jQfcVOO6afg7671FQ5PDb8nLHUJg
[DEBUG]	2022-08-25T08:41:18.847Z	5d6d3f01-817e-43db-b74d-117d6aadd6ec	Starting new HTTPS connection (1):MyInstance.my.salesforce.com:443
[DEBUG]	2022-08-25T08:41:19.060Z	5d6d3f01-817e-43db-b74d-117d6aadd6ec	https://MyInstance.my.salesforce.com:443 "POST /services/oauth2/token HTTP/1.1" 400 None
[DEBUG]	2022-08-25T08:41:19.063Z	5d6d3f01-817e-43db-b74d-117d6aadd6ec	<Response [400]>

and my test was left as default
`{
  "key1": "value1",
  "key2": "value2",
  "key3": "value3"
}`

**Comment by dougjaso** [comment]
Is this actually the username that you created during your setup:  'awsutil@.com'

**Comment by konungr5583** [comment]
No, but everything is working so thank you

**Comment by dcarbonetti** [comment]
Doublecheck your username, ***@***.*** doesnt seem right
