### ISSUE TITLE
SF Case not created, strange error in CloudWatch

### ISSUE THREAD

**Issue by chrisansotti** [amazon-connect/amazon-connect-salesforce-scv#141]
Just completed configuring VMX2 in a production instance but no cases are getting created and I'm seeing a weird error in CloudWatch (below). The recordings and transcriptions are making it into the S3 bucket in AWS, but no Case in SF. I've triple checked the settings and compared them to the sandbox where everything is working perfectly, can't see any config issues.

Field
Value
@ingestionTime
1664511723046
@log
246162452998:/aws/lambda/VMXPackager-goloprod00d6g000000ttsy
@logStream
2022/09/30/[$LATEST]b51ec9c54c4c40d9aeca6993fcb74f4f
@message
[ERROR] 2022-09-30T04:21:59.975Z 1bb14ec3-84c3-42fe-b531-0e4dfb289be1 list indices must be integers or slices, not str
@requestId
1bb14ec3-84c3-42fe-b531-0e4dfb289be1
@timestamp
1664511719975

**Comment by dougjaso** [comment]
Is this voicemail going to a queue or to an agent?

Sent from my iPhone

On Sep 29, 2022, at 9:37 PM, chrisansotti ***@***.***> wrote:

﻿

Just completed configuring VMX2 in a production instance but no cases are getting created and I'm seeing a weird error in CloudWatch (below). The recordings and transcriptions are making it into the S3 bucket in AWS, but no Case in SF. I've triple checked the settings and compared them to the sandbox where everything is working perfectly, can't see any config issues.

Field
Value
@ingestionTime
1664511723046
@log<https://github.com/log>
246162452998:/aws/lambda/VMXPackager-goloprod00d6g000000ttsy
@logstream<https://github.com/logstream>
2022/09/30/[$LATEST]b51ec9c54c4c40d9aeca6993fcb74f4f
@message<https://github.com/message>
[ERROR] 2022-09-30T04:21:59.975Z 1bb14ec3-84c3-42fe-b531-0e4dfb289be1 list indices must be integers or slices, not str
@requestid<https://github.com/requestid>
1bb14ec3-84c3-42fe-b531-0e4dfb289be1
@timestamp<https://github.com/timestamp>
1664511719975

**Comment by chrisansotti** [comment]
Going to a queue. I made sure they all have descriptions, too.

**Comment by dougjaso** [comment]
Did you deploy the solution as a Production (not Sandbox)?

**Comment by chrisansotti** [comment]
Yes, assuming you mean the parameter setting in this screenshot:

<img width="316" alt="Screen Shot 2022-09-30 at 10 55 52 AM" src="https://user-images.githubusercontent.com/111243896/193309816-accccc46-bfcf-4333-aeda-a35a4fcca63d.png">

**Comment by dougjaso** [comment]
In this case, we had to set the visibility for the custom fields. Interesting to see if others experience this. Perhaps something new with Winter.
