### ISSUE TITLE
Voicemail Setup rolling back

### ISSUE THREAD

**Issue by Cusack84** [amazon-connect/amazon-connect-salesforce-scv#144]
I'm admittedly very new to doing something like this.  But I need to get voicemail funcationality working.  Looking to have amazon connect calls that end up in voicemail create an object that goes into a queue.  This looked like the right place to implement this solution but the stack creation does a rollback on me.

The following resource(s) failed to create: [CopyLambdaArtifactsStack, SolutionHelperFunction]. Rollback requested by user.

Resource creation cancelled

Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs16.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: ffd0dec1-e3d6-4c8d-bd03-1d01f2a20d53)" (RequestToken: 8098a0df-96f7-ef2a-a93f-420bea9c5275, HandlerErrorCode: InvalidRequest)

Is this something I'm doing wrong or something maybe someone can point me in the right direction?  I'd appreciate it

**Comment by dougjaso** [comment]
Before you go down this route, are you trying to setup voicemail for Service Cloud Voice or just standalone Amazon Connect?

**Comment by Cusack84** [comment]
Voicemail for Service Cloud Voice.

**Comment by dougjaso** [comment]
SO 2 things: 
1. can you provide a link to the template/instructions that you are using?
2. Have you considered using the newly released v[oicemail option for Service Cloud Voice that Salesforce has embedded into the offering](https://help.salesforce.com/s/articleView?id=release-notes.rn_voice_route_play_back_voicemails.htm&type=5&release=240)?

**Comment by dougjaso** [comment]
no further communication
