### ISSUE TITLE
Issue w/ VoiceMailAudioProcessingFunction 

### ISSUE THREAD

**Issue by rryke** [amazon-connect/amazon-connect-salesforce-scv#153]
Hi all, 
When I am working through the test flow. I get an error on the send voicemail directly to an agent flow. It looks like this particular function errors with: 

```
"errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "BadRequest: Object tags cannot be greater than 10",
    "reason": {
        "errorType": "BadRequest",
        "errorMessage": "Object tags cannot be greater than 10",
        "code": "BadRequest",
        "message": "Object tags cannot be greater than 10",
        "region": "us-west-2",
```

I'm assuming that this is trying to write to an object to s3 with more than 10 tags. I tried removing attributes to see if the attributes were being written to tags. But that didn't seem to make a difference.

**Comment by dougjaso** [comment]
HAre you using the test flows or your own implementation? And which version of the function are you using (can be fouind by looking at the EXPTemplateVersion parameter in your cloudformation template)? I just tested this on a clean install and did not encounter this issue.

**Comment by rryke** [comment]
Running the canned test flows. 
2022.03.23

**Comment by rryke** [comment]
Closing this. Moving to the Salesforce solution thank you @dougjaso
