### ISSUE TITLE
Amazon Connect - Get Current User Data is not available in the aws-java-sdk-connect 

### ISSUE THREAD

**Issue by Nithishsubramaiyan** [amazon-connect/amazon-connect-salesforce-scv#154]
I'm trying to get real time agent's state using amazon connect API but in connect sdk I don't find any class or method to get user data metrics.

I want to show the real time agent state in a dashboard to sales force client but can't

I cound get the same metrics at connect.us-east-1.amazonaws.com/metrics/userdata/

**Comment by dougjaso** [comment]
This is not related to the tools in this repository. 

[This API action is what you are looking for](https://docs.aws.amazon.com/cli/latest/reference/connect/get-current-user-data.html)
