### ISSUE TITLE
Voicemail Express 2 CF Template not working

### ISSUE THREAD

**Issue by bnirwan** [amazon-connect/amazon-connect-salesforce-scv#157]
Getting this error when using the vmx.yaml. Can you please check and do the needful -

Your access has been denied by S3, please make sure your request credentials have permission to GetObject for connectbd-sc-us-east-1/sf_config/2023.05.11/zip/awsscv_common_node.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 58e64e58-ad17-49d2-9b37-c6dd7b7f4473; Proxy: null)

The problem is even the old vmx.yaml which used to work earlier is also failing for trigger stack. I see there are some changes moving to event bridge. So I downloaded latest one but that is also not working.

@dougjaso  Please fix it on priority. I am stuck due to the issue.

Thanks

**Comment by dougjaso** [comment]
This should be resolved. Please let me know if you continue to see the error.

**Comment by bnirwan** [comment]
Thanks a lot .it works now.
