### ISSUE TITLE
Voicecall record is getting created along with salesforce case record during Voicemail creation

### ISSUE THREAD

**Issue by sureka-ark** [amazon-connect/amazon-connect-salesforce-scv#174]
Hi @dougjaso,

In Previous Versions, It is only creating sf case record with origin as "VOICEMAIL" but
In current version, 

1. Sf case record is getting created with origin as "PHONE" and voicecall record is also getting created
2. We can't see any differences for this voicecall record and the record which is created when agents attends the customer call
3. And the sf case record (created during voicemail) is not connected to the voicecall.

**Comment by Manvi7022** [comment]
Hi @dougjaso 

Could you please tell us if any one of the below is possible-

1. when a voicemail creates VoiceCall Record, the Call type for that voiceCall record should be "Voicemail" . I see that the 'Call Type' Picklist field already have a value as "Voicemail". But its not picking that value. 

2. How do we stop creating VoiceCall Record for Voicemails.

Kindly provide steps to achieve any one of these. 
Thanks in Advance!

**Comment by sureka-ark** [comment]
Hi @dougjaso 

While exploring the code in CTRDataSyncFunction lambda function, we found that there is a vm_flag is called. Changed that vm_flag to vmx_flag. Now it is not creating voicecall for voicemail.

Thanks

**Comment by dougjaso** [comment]
Salesforce now includes voicemail, based on this solution, with SCV. You are now running two versions of voicemail. For long term support purposes, you should migrate to the Salesforce provided version:
https://developer.salesforce.com/docs/atlas.en-us.voice_developer_guide.meta/voice_developer_guide/voice_example_voicemail.htm


-----------
Jason Douglas
Principal Solutions Architect
Amazon Connect

704.807.6561 – mobile
415.262.9741 – office

[signature_2001959500]<http://www.aws.amazon.com/>

Thoughts on our interaction? Provide feedback here<https://feedback.aws.amazon.com/?ea=dougjaso&fn=Jason&ln=Douglas>.


From: Sureka A R K ***@***.***>
Reply-To: amazon-connect/amazon-connect-salesforce-scv ***@***.***>
Date: Monday, August 5, 2024 at 2:20 AM
To: amazon-connect/amazon-connect-salesforce-scv ***@***.***>
Cc: "Douglas, Jason" ***@***.***>, Mention ***@***.***>
Subject: [amazon-connect/amazon-connect-salesforce-scv] Voicecall record is getting created along with salesforce case record during Voicemail creation (Issue #174)


Hi @dougjaso<https://github.com/dougjaso>,

In Previous Versions, It is only creating sf case record with origin as "VOICEMAIL" but
In current version,

  1.  Sf case record is getting created with origin as "PHONE" and voicecall record is also getting created
  2.  We can't see any differences for this voicecall record and the record which is created when agents attends the customer call
  3.  And the sf case record (created during voicemail) is not connected to the voicecall.

**Comment by dougjaso** [comment]
This repository does not provide a voicemail application that creates VoiceCall objects, only the native voicemail option included with Service Cloud Voice does that. If you do not wish to use the Salesforce-provided version, simply remove the trigger for the Salesforce Lambdas. More info can be found here: https://github.com/amazon-connect/amazon-connect-salesforce-scv/issues/165

-----------
Jason Douglas
Principal Solutions Architect
Amazon Connect

704.807.6561 – mobile
415.262.9741 – office

[signature_2001959500]<http://www.aws.amazon.com/>

Thoughts on our interaction? Provide feedback here<https://feedback.aws.amazon.com/?ea=dougjaso&fn=Jason&ln=Douglas>.


From: Manvitha K ***@***.***>
Reply-To: amazon-connect/amazon-connect-salesforce-scv ***@***.***>
Date: Tuesday, August 6, 2024 at 7:46 PM
To: amazon-connect/amazon-connect-salesforce-scv ***@***.***>
Cc: "Douglas, Jason" ***@***.***>, Mention ***@***.***>
Subject: Re: [amazon-connect/amazon-connect-salesforce-scv] Voicecall record is getting created along with salesforce case record during Voicemail creation (Issue #174)


Hi @dougjaso<https://github.com/dougjaso>

Could you please tell us if any one of the below is possible-

  1.  when a voicemail creates VoiceCall Record, the Call type for that voiceCall record should be "Voicemail" . I see that the 'Call Type' Picklist field already have a value as "Voicemail". But its not picking that value.
  2.  How do we stop creating VoiceCall Record for Voicemails.

Kindly provide steps to achieve any one of these.
Thanks in Advance!
