### ISSUE TITLE
Incorrect steps documented

### ISSUE THREAD

**Issue by amit-gayal** [amazon-connect/amazon-connect-salesforce-scv#20]
Hi Team,

I followed the steps as documented and ran into some errors. Then did some changes in code and IAM permissions, after which the **Voicemail solution** worked.

**Issue 1:**
In **sf_auth.py** file, line 63:
`jwt = self.generate_jwt(jwt_payload, base64.b64decode(settings[SalesforceConfig.PRIVATE_KEY_PROP]))`

The second parameter is decoded whereas the **Step 11.f** in [Salesforce Pre-requisite](https://github.com/amazon-connect/amazon-connect-salesforce-scv/tree/master/common/AWSSCV-SalesforceConfig) says that we need to copy the content from **server.key** file. See below:

_f. sfPrivateKey: The content of the server.key private key that you generated as a part of the setup process. You should only copy the content between the BEGIN and END lines_

**Proposed resolution:** 
Either we need to update the documentation to say **copy the text from encoded_key.txt** file **OR** update the code to use the key as it is.

=======================================================================================

**Issue 2:**
After resolving issue 1, I ran into error as below:

_An error occurred (AccessDeniedException) when calling the UpdateSecret operation: User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/awsscv_common_role/AWSSCV_vmx_packager_XXXXXXXXXXXXXX is not authorized to perform: secretsmanager:UpdateSecret on resource: arn:aws:secretsmanager:yy-yyyy-n:XXXXXXXXXXXX:secret:awsscv_salesforce_config_XXXXXXXXXXXXXXXXXXXXXXXXX_

**Proposed resolution:** 
Update the CF template to include **secretsmanager:UpdateSecret** permission to **awsscv_common_secrets_policy** IAM policy.

**Comment by dougjaso** [comment]
Corrected and updated.
