### ISSUE TITLE
Incorrect AUDIENCE

### ISSUE THREAD

**Issue by amit-gayal** [amazon-connect/amazon-connect-salesforce-scv#31]
**Issue found in Layer for packager function:**

The AUDIENCE variable in awsscv > sf_config.py is set to **login.salesforce.com**
AUDIENCE = 'https://login.salesforce.com'

This causes issue while getting an authentication token if the solution is getting installed in a sandbox. 

For sandbox, it should be **test.salesforce.com**

Hence this should be made dynamic based on the environment.

**Comment by SteveEarl-AWS** [comment]
I'll be rolling out a fix for this issue in the next few days.

**Comment by SteveEarl-AWS** [comment]
Fix has been applied.
