### ISSUE TITLE
Usage of Kinesis Video Streams

### ISSUE THREAD

**Issue by kazuki1126** [amazon-connect/amazon-connect-salesforce-scv#57]
In the 4 steps describing how to set up the voicemail feature between Amazon Connect and Salesforce,
there's no mention on how to set up Kinesis Video Streams(KVS) or if we need to set it up in the first place. 
But KVS is placed in the overall architecture diagram of Readme. So I wondered if KVS is actually needed to use Voicemail Express and thought it could be a missing part in the doc.

**Comment by kazuki1126** [comment]
FYI: 
I'm referring to this page for the architecture diagram and set up process ↓
https://github.com/amazon-connect/amazon-connect-salesforce-scv/tree/master/Solutions/AWSSCV-VoicemailExpress

**Comment by dougjaso** [comment]
KVS is enabled and configured by default in all Service Cloud Voice configurations.

**Comment by dougjaso** [comment]
Closed.
