### ISSUE TITLE
warming example for kvsConsumerTrigger needs to define result{}

### ISSUE THREAD

**Issue by johnny2678** [amazon-connect/amazon-connect-salesforce-scv#58]
https://github.com/amazon-connect/amazon-connect-salesforce-scv/tree/master/Examples/AWSSCV-WarmingFunctions/Code/kvsConsumerTrigger

If you use this code, you'll get an `"errorMessage":"result is not defined"` error when testing 

fixed by putting `    let result = {};` before line 14

**Comment by dougjaso** [comment]
Corrected. Thank you.
