### ISSUE TITLE
Can't find `awsscv` in pip

### ISSUE THREAD

**Issue by noce2** [amazon-connect/amazon-connect-salesforce-scv#64]
Hi,

The lambda common layers reference a library that can't be found in pip or Conda. Please could you confirm if this is a private package?

https://github.com/amazon-connect/amazon-connect-salesforce-scv/blob/d8eedba2205d32fbd7ca21455a32914214f11d28/Common/AWSSCV-CommonLayers/Code/python-layer/python/lib/python3.8/site-packages/requirements.txt#L1

**Comment by dougjaso** [comment]
It is a private package developed specifically for these use cases.
