### ISSUE TITLE
Latest Python Common Layer causes cffi backend error in validator

### ISSUE THREAD

**Issue by dcarbonetti** [amazon-connect/amazon-connect-salesforce-scv#68]
After a lot of troubleshooting between my dev and test orgs for a client (built days apart) ive found that there looks to be a version release done to the common python layer (38 vs 39) that seems to cause the validator to spit out an error

No module named '_cffi_backend'

**Comment by dcarbonetti** [comment]
Ive manually uploaded a zip of the previous version of the python common layer as a workaround which fixed the issue

**Comment by jeremy-hayes** [comment]
@dcarbonetti do you know where we can find a zip of the previous version of the python common layer?

**Comment by jeremy-hayes** [comment]
@dcarbonetti Disregard, we pulled an old version from dev.  Thank you very much for supplying the workaround!

**Comment by corentinbernier** [comment]
[awsscv_common_python-068ce42a-b848-48da-8927-097cbbb23d3b.zip](https://github.com/amazon-connect/amazon-connect-salesforce-scv/files/7127220/awsscv_common_python-068ce42a-b848-48da-8927-097cbbb23d3b.zip)
We've had the same problem with our latest installation and uploading this file as a new version of the awsscv_common_python fixed it.

**Comment by dougjaso** [comment]
Reviewing this fix. WIll update today.

**Comment by VigeashGobal** [comment]
@corentinbernier Can you explain how to upload the file as a new version.  When i try uploading the zip it doesn't work

**Comment by VigeashGobal** [comment]
@dcarbonetti Can you please provide where that old version is, I cannot seem to find it.  Really appreciate the help

Thanks,

**Comment by dcarbonetti** [comment]
> @dcarbonetti Can you please provide where that old version is, I cannot seem to find it. Really appreciate the help
> 
> Thanks,

Here's a step by step:
1. Download the Zip file provided by @corentinbernier ( https://github.com/amazon-connect/amazon-connect-salesforce-scv/files/7127220/awsscv_common_python-068ce42a-b848-48da-8927-097cbbb23d3b.zip)
2. log into AWS console
3. navigate to Lambda
4. select "Layers" on the left hand side menu
5. click on the "awsscv_common_python" (or equivalent)
6. click on the "create version" button on the top right
7. upload the zip file you previously downloaded
8. click create

after that you will need to just doublecheck that all of the other python based lambdas are pointing to the correct version

**Comment by VigeashGobal** [comment]
Thank you so much!

**Comment by dougjaso** [comment]
This has been fixed in the latest build
