### ISSUE TITLE
Case not being created

### ISSUE THREAD

**Issue by VigeashGobal** [amazon-connect/amazon-connect-salesforce-scv#72]
Hello,

If anyone can help with this it would be greatly appreciated 
I currently have my connection set but the case is not being generated, this is the error I see.

Thank you,

Test Event Name
test

Response
{
  "errorMessage": "'Records'",
  "errorType": "KeyError",
  "stackTrace": [
    "  File \"/var/task/awsscv_vmx_packager.py\", line 35, in lambda_handler\n    for record in event['Records']:\n"
  ]
}

Function Logs
START RequestId: f4c59ed3-a847-46e5-8115-73016055629e Version: $LATEST
[INFO]	2021-09-14T16:50:16.553Z	f4c59ed3-a847-46e5-8115-73016055629e	Found credentials in environment variables.
[ERROR] KeyError: 'Records'
Traceback (most recent call last):
  File "/var/task/awsscv_vmx_packager.py", line 35, in lambda_handler
    for record in event['Records']:END RequestId: f4c59ed3-a847-46e5-8115-73016055629e
REPORT RequestId: f4c59ed3-a847-46e5-8115-73016055629e	Duration: 848.81 ms	Billed Duration: 849 ms	Memory Size: 128 MB	Max Memory Used: 82 MB	Init Duration: 368.40 ms

Request ID
f4c59ed3-a847-46e5-8115-73016055629e

**Comment by VigeashGobal** [comment]
To provide more clarity to the problem above, when running the packager lambda function I am getting an error on the getsecret function which is stating the secret is not alpha numeric.  Any help or direction would be amazing thank you very much!

**Comment by dcarbonetti** [comment]
First up, i dont think this is an issue worh the package itself as its working fine when others have installed it, so chances are you are doing something wrong. You also mentioned “running” the lambda, just wanting to confirm you’re not actually trying to call it from the contact flow directly 

can I also confirm:
You have completed the prerequisite steps and set up a connected app for the integration 

You have set up the required events and triggers

You have run a test in the validator and if so can you add in the Content of the success message you receive when you run the test

**Comment by VigeashGobal** [comment]
Hi Diego,

You were completely right i made a mistake copying the ARN.  Thank you very much for your help!

Cheers,
