### ISSUE TITLE
vm_lang error

### ISSUE THREAD

**Issue by tsabat** [amazon-connect/amazon-connect-salesforce-scv#83]
We're seeing this in the error log:

[ERROR]	2022-02-03T18:31:49.261Z	0483faff-6fe4-4ed1-bf04-4495b509f14e	'vm_lang'

And the call was never recorded.  Any advice?

**Comment by tsabat** [comment]
Oh, possible this is a config issue on our end.  Engineer on the case says

> that was on the straight out of hte box flow with no attributes assigned, so looks like the language wasn't set to US

Does that sound right?  If so, we'll close this issue.

**Comment by dougjaso** [comment]
yes, in the contact flows that invoke the voicemail flow, you need to set the language as a contact attribute named vm_lang. This is shown in the test flow.

**Comment by dougjaso** [comment]
vm_lang = en-US or appropriate language.
