### ISSUE TITLE
 Fall of the function such AWSSCV_vmx_kvs_to_s3 depending on the queue of the queue to be set

### ISSUE THREAD

**Issue by gusersv** [amazon-connect/amazon-connect-salesforce-scv#88]
Hello,

We have implemented the AWSSCV-VoicemailExpress solution to create a voicemail in Salesforce Voice.

In general it is working fine [1], however we noticed that for certain queues set on the Amazon Connect flow it fails [2]. We have faithfully followed the steps of the provided guide and we do not understand the reason for the punctual failure.

Thanks.

[1] [CorrectWork.txt](https://github.com/amazon-connect/amazon-connect-salesforce-scv/files/8185334/CorrectWork.txt)
[2] [Error log.txt](https://github.com/amazon-connect/amazon-connect-salesforce-scv/files/8185476/Error.log.txt)

**Comment by dougjaso** [comment]
Does the queue that fails ALWAYS fail? Are there other queues that ALWAYS fail?

**Comment by gusersv** [comment]
Yes, the queue seen in the log has failed every time. As well as two others.

**Comment by dcarbonetti** [comment]
I noticed this on the error

vm_lang: 'es-US',

The success had

vm_lang: 'es-ES',

Maybe try updating the es-US to es-Es for that contact flow

**Comment by dougjaso** [comment]
This is a resuklt
